import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import 'aos/dist/aos.css';
import "./globals.css";
import "./responsive.css";
import Header from "./header/Header";
import Footer from "./footer/Footer";
import "./font/IBMPlexMono/stylesheet.css";
import "./font/Anuv_handwriting/stylesheet.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anuv Jain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Header />
       
      </body>
    </html>
  );
}
